#!/usr/bin/env bash
# borg-backup-${BACKUP_CLIENT_NAME} — generated by setup-backup-client.sh on ${GENERATED_DATE}.
# Re-run setup-backup-client.sh to regenerate; do not edit by hand.
#
# Repo: ${REPO_URI}
# Stale lock recovery: 'borg break-lock <repo>' is DANGEROUS while a backup
# may still run — only do it after confirming no run is in flight.

set -euo pipefail

CLIENT="${BACKUP_CLIENT_NAME}"
REPO_URI="${REPO_URI}"
PASSPHRASE_FILE="${PASS_FILE}"
BORG_RSH='${BORG_RSH}'

BACKUP_PATHS_RAW='${BACKUP_PATHS}'
read -r -a BACKUP_PATHS <<< "${BACKUP_PATHS_RAW}"

BACKUP_SERVICES='${BACKUP_SERVICES}'
BACKUP_STOP_SERVICES='${BACKUP_STOP_SERVICES}'
BACKUP_STAGING_DIR='${BACKUP_STAGING_DIR}'
REPO_MOUNT_SOURCE='${REPO_MOUNT_SOURCE}'
KEEP_DAILY=${BACKUP_KEEP_DAILY}
KEEP_WEEKLY=${BACKUP_KEEP_WEEKLY}
KEEP_MONTHLY=${BACKUP_KEEP_MONTHLY}
COMPRESSION=${BACKUP_COMPRESSION}
ONE_FILE_SYSTEM=${BACKUP_ONE_FILE_SYSTEM}

EXCLUDES=(${EXCLUDES_BLOCK})

LIB="/usr/local/lib/borg-backup/docker-backup.sh"

# apt borg 1.x reads BORG_PASSPHRASE (the *_FILE variants are borg 2.x only),
# so the stored file is read into the env at run time — never printed, never
# logged (journal does not expose process environment).
if [[ ! -f "${PASSPHRASE_FILE}" ]]; then
  echo "ERROR: passphrase file missing: ${PASSPHRASE_FILE}" >&2
  exit 1
fi
BORG_PASSPHRASE="$(cat "${PASSPHRASE_FILE}")"
export BORG_PASSPHRASE
if [[ -n "${BORG_RSH}" ]]; then
  export BORG_RSH
fi
# shellcheck disable=SC1090,SC1091
source "${LIB}"

QUIESCED=()

_quiesce_resume_all() {
  local svc
  for svc in "${QUIESCED[@]}"; do
    bk_stack_resume "$svc" || bk_warn "failed to resume ${svc} — start it manually"
  done
  QUIESCED=()
}
trap '_quiesce_resume_all' EXIT

usage() {
  cat <<'USAGE'
borg-backup-${BACKUP_CLIENT_NAME} <command> [args]

Commands:
  create                             Dump configured services, then 'borg create' + 'borg prune'
  list                               List the 20 newest snapshots
  check [--full]                     Repository integrity check (--full: read all data)
  restore <snapshot> [--dest DIR] [paths...]
                                     Extract a snapshot to DIR (default ./restore-${BACKUP_CLIENT_NAME}-<ts>);
                                     paths as stored in the archive (leading / is stripped)
  restore-db <snapshot> <service> --yes
                                     DESTRUCTIVE: restore one service's database from its dump

Environment:
  BORG_PASSPHRASE is read from the passphrase file by this wrapper; everything
  else is baked in.
USAGE
}

create() {
  local ts svc re
  ts="$(date '+%Y-%m-%dT%H:%M:%S')"

  # Local-mode mount guard: if the backup drive is not mounted at the repo
  # path anymore (e.g. after a reboot without fstab entry), refuse to write
  # borg chunks into the root filesystem.
  if [[ -n "${REPO_MOUNT_SOURCE}" ]]; then
    local current_source
    current_source="$(findmnt -n -o SOURCE --target "${REPO_URI}" 2>/dev/null || true)"
    if [[ "$current_source" != "${REPO_MOUNT_SOURCE}" ]]; then
      echo "ERROR: backup drive does not appear mounted at the repo path — refusing to write backups into the root filesystem; re-run setup-backup-client.sh after fixing the mount" >&2
      exit 2
    fi
  fi

  if [[ -n "${BACKUP_STOP_SERVICES}" ]]; then
    for svc in ${BACKUP_STOP_SERVICES//,/ }; do
      bk_stack_quiesce "$svc" || { _quiesce_resume_all; exit 2; }
      QUIESCED+=("$svc")
    done
  fi

  if [[ -n "${BACKUP_SERVICES}" ]]; then
    bk_staging_init "${BACKUP_STAGING_DIR}" || { _quiesce_resume_all; exit 2; }
    bk_staging_clean "${BACKUP_STAGING_DIR}" || { _quiesce_resume_all; exit 2; }
    for svc in ${BACKUP_SERVICES//,/ }; do
      if ! bk_dump_service "$svc" "${BACKUP_STAGING_DIR}"; then
        bk_error "dump of ${svc} failed — aborting before 'borg create'; partial dumps kept at ${BACKUP_STAGING_DIR}/dumps for debugging" || true
        _quiesce_resume_all
        exit 2
      fi
    done
  fi

  local -a args=(--stats --compression "${COMPRESSION}")
  if [[ "${ONE_FILE_SYSTEM}" == true ]]; then
    args+=(--one-file-system)
  fi
  args+=(--exclude-caches)
  for re in "${EXCLUDES[@]}"; do
    args+=(--exclude "$re")
  done

  local -a sources=("${BACKUP_PATHS[@]}")
  if [[ -n "${BACKUP_SERVICES}" ]]; then
    sources+=("${BACKUP_STAGING_DIR}")
  fi

  bk_info "borg create ${REPO_URI}::${CLIENT}-${ts} (sources: ${sources[*]})"
  # borg exit 1 = warnings (unreadable/changed files — normal when a regular
  # user backs up /etc): the archive is complete, retention must still run.
  # Exit >= 2 (lock, ENOSPC, I/O, remote) is fatal.
  local create_rc=0
  # shellcheck disable=SC2140  # borg's "repo::archive" syntax
  borg create "${args[@]}" "${REPO_URI}"::"${CLIENT}-${ts}" "${sources[@]}" || create_rc=$?
  if (( create_rc >= 2 )); then
    bk_error "borg create failed (rc=${create_rc})"
    exit "${create_rc}"
  fi
  if (( create_rc == 1 )); then
    bk_warn "borg create finished WITH WARNINGS (unreadable/changed files) — archive is usable; see above"
  fi

  bk_info "borg prune (keep daily=${KEEP_DAILY} weekly=${KEEP_WEEKLY} monthly=${KEEP_MONTHLY})"
  borg prune --glob-archives "${CLIENT}-*" \
    --keep-daily "${KEEP_DAILY}" --keep-weekly "${KEEP_WEEKLY}" --keep-monthly "${KEEP_MONTHLY}" \
    "${REPO_URI}"

  if [[ -n "${BACKUP_SERVICES}" ]]; then
    bk_staging_clean "${BACKUP_STAGING_DIR}" || bk_warn "staging cleanup failed — remove ${BACKUP_STAGING_DIR}/dumps manually"
  fi
  bk_info "create finished: ${CLIENT}-${ts}"
}

list() {
  borg list --short "${REPO_URI}" | tail -n 20
}

check() {
  local -a extra=()
  # --verify-data: apt borg 1.x name for a full data check (borg 2.x: --read-data)
  if [[ "${1:-}" == "--full" ]]; then
    extra=(--verify-data)
  fi
  borg check "${extra[@]}" "${REPO_URI}"
}

restore() {
  local snap="${1:?snapshot required}"; shift
  local dest
  dest="./restore-${CLIENT}-$(date '+%Y-%m-%dT%H%M%S')"
  local -a paths=()
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --dest) dest="${2:?--dest needs a value}"; shift 2 ;;
      *) paths+=("${1#/}"); shift ;;
    esac
  done
  mkdir -p "$dest"
  bk_info "restoring ${REPO_URI}::${snap} -> ${dest}"
  # borg 1.x has no --destination: it extracts into the CWD (absolute paths
  # stored in the archive are re-created under it). A fresh dest dir keeps
  # restores out-of-place by construction.
  ( cd "$dest" && borg extract --progress "${REPO_URI}"::"${snap}" "${paths[@]}" )
  bk_info "restore complete: $dest"
}

restore_db() {
  local snap="${1:?snapshot required}" svc="${2:?service required}" confirmed="no"
  if [[ "${3:-}" == "--yes" ]]; then
    confirmed="yes"
  fi
  if [[ "$confirmed" != "yes" ]]; then
    bk_error "restore-db is DESTRUCTIVE (drops and re-creates ${svc}'s database). Re-run with --yes." || true
    return 1
  fi
  local tmp latest
  tmp="$(mktemp -d)"
  bk_info "extracting ${BACKUP_STAGING_DIR}/dumps for ${svc} from ${snap}"
  if ! ( cd "${tmp}" && borg extract --progress "${REPO_URI}"::"${snap}" "${BACKUP_STAGING_DIR#/}/dumps" ); then
    bk_error "extraction failed — does snapshot ${snap} contain dumps? (BACKUP_SERVICES was probably empty when it was created)" || true
    rm -rf "${tmp}"
    return 1
  fi

  shopt -s nullglob
  local -a files=("${tmp}${BACKUP_STAGING_DIR}/dumps/${svc}-"*)
  shopt -u nullglob
  if (( ${#files[@]} == 0 )); then
    rm -rf "$tmp"
    bk_error "no ${svc} dump found in snapshot ${snap}" || true
    return 1
  fi
  latest="${files[-1]}"

  if ! bk_restore_db "$svc" "${latest}"; then
    bk_error "restore failed; dump kept at ${latest} for retry" || true
    return 1
  fi
  rm -rf "$tmp"
  bk_info "database restore complete for ${svc}"
}

case "${1:-help}" in
  create)     shift; create "$@" ;;
  list)       shift; list ;;
  check)      shift; check "$@" ;;
  restore)    shift; restore "$@" ;;
  restore-db) shift; restore_db "$@" ;;
  help|--help|-h) usage ;;
  *) echo "Unknown command: $1" >&2; usage >&2; exit 1 ;;
esac
